apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alpha
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-alpha
  template:
    metadata:
      labels:
        app: app-alpha
        team: qa
    spec:
      containers:
      - name: app-alpha
        image: busybox
        command: ["sleep", "3600"]
        volumeMounts:
        - name: host-volume
          mountPath: /host
      volumes:
      - name: host-volume
        hostPath:
          path: /etc
